# Generated by Django 4.2 on 2024-04-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_posts_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='user',
        ),
    ]
