# Generated by Django 4.2 on 2024-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_user_id_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='price',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
